# This notebook is simply used for initial data's location analysis

Feel free to use for anything regarding location data in here :)

In [2]:
# Load libraries
import pandas as pd
import geopandas as gpd
from shapely.geometry import shape, Point
import os
import folium

In [38]:
# Load data

sf_east = gpd.read_file("../data/location/cbd_east/shp/sa1_2016_aust-.shp")
sf_north = gpd.read_file("../data/location/cbd_north/shp/sa1_2016_aust-.shp")
sf_west = gpd.read_file("../data/location/cbd_west/shp/sa1_2016_aust-.shp")
dev_act_monitor = pd.read_csv("../data/predictor/Pedestrian Sensor Locations.csv")

# sf_east['geometry'] = sf_east['geometry'].to_crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# sf_north['geometry'] = sf_north['geometry'].to_crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
# sf_west['geometry'] = sf_west['geometry'].to_crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

In [4]:
# The only 2 columns we need are location code and its location information:

KEY_LOCATION_COLUMNS=['sa1_7digi7', 'geometry']

sf_west[KEY_LOCATION_COLUMNS].head(5)

  sa1_7digi7                                           geometry
0    2111804  POLYGON ((144.95183 -37.82183, 144.95204 -37.8...
1    2111811  POLYGON ((144.94761 -37.81425, 144.94719 -37.8...
2    2111815  POLYGON ((144.94849 -37.81847, 144.95030 -37.8...
3    2111816  POLYGON ((144.94869 -37.82066, 144.94946 -37.8...
4    2111911  POLYGON ((144.97682 -37.81740, 144.97731 -37.8...

In [5]:
sf_east[KEY_LOCATION_COLUMNS].head(5)

  sa1_7digi7                                           geometry
0    2111709  POLYGON ((144.96755 -37.80590, 144.96770 -37.8...
1    2111724  POLYGON ((144.97433 -37.80122, 144.97408 -37.8...
2    2111731  POLYGON ((144.96454 -37.80586, 144.96473 -37.8...
3    2111910  POLYGON ((144.97319 -37.80792, 144.97404 -37.8...
4    2111911  POLYGON ((144.97682 -37.81740, 144.97731 -37.8...

In [6]:
sf_north[KEY_LOCATION_COLUMNS].head(5)

  sa1_7digi7                                           geometry
0    2111707  POLYGON ((144.95994 -37.80634, 144.95950 -37.8...
1    2111710  POLYGON ((144.96314 -37.80525, 144.96326 -37.8...
2    2111731  POLYGON ((144.96454 -37.80586, 144.96473 -37.8...
3    2112202  POLYGON ((144.95889 -37.81104, 144.95853 -37.8...
4    2112203  POLYGON ((144.95802 -37.81007, 144.95840 -37.8...

In [8]:
dev_act_monitor.columns

Index(['Location_ID', 'Sensor_Description', 'Sensor_Name', 'Installation_Date',
       'Note', 'Location_Type', 'Status', 'Direction_1', 'Direction_2',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [9]:
dev_act_monitor[['Latitude', 'Longitude', 'Location']]

      Latitude   Longitude                    Location
0   -37.818880  144.954492  -37.81887963, 144.95449198
1   -37.824018  144.956044  -37.82401776, 144.95604426
2   -37.816525  144.961211  -37.81652527, 144.96121062
3   -37.803103  144.966715  -37.80310271, 144.96671451
4   -37.816686  144.966897  -37.81668634, 144.96689733
..         ...         ...                         ...
135 -37.807812  144.958222   -37.80781158, 144.9582219
136 -37.807716  144.958624   -37.80771581, 144.9586238
137 -37.807804  144.958298  -37.80780367, 144.95829765
138 -37.818213  144.945773  -37.81821294, 144.94577313
139 -37.806516  144.960079  -37.80651646, 144.96007934

[140 rows x 3 columns]

In [58]:
i = 0
for coord in dev_act_monitor[['Location']].iterrows():
    coord = coord[1][0].split(",")
    lat = coord[0]
    long = coord[1]
    point = Point(long, lat)
    inside_east = False
    inside_west = False
    inside_north = False

    for poly in sf_east['geometry']:
        if poly.contains(point):
            inside_east = True
    
    for poly in sf_west['geometry']:
        if poly.contains(point):
            inside_west = True

    for poly in sf_north['geometry']:
        if poly.contains(point):
            inside_north = True

    if (inside_east == True) or (inside_north == True) or (inside_west == True):
        print(f"{i}'th point:")
        print(f"east: {inside_east}")
        print(f"north: {inside_north}")
        print(f"west: {inside_west}")
    else:
        print(f"{i}'th point was out of bounds")
    i += 1

0'th point:
east: False
north: False
west: True
1'th point:
east: False
north: False
west: True
2'th point:
east: True
north: False
west: True
3'th point was out of bounds
4'th point:
east: True
north: False
west: True
5'th point:
east: True
north: True
west: True
6'th point was out of bounds
7'th point:
east: False
north: True
west: False
8'th point was out of bounds
9'th point:
east: True
north: True
west: True
10'th point:
east: True
north: True
west: True
11'th point:
east: True
north: False
west: True
12'th point:
east: True
north: True
west: True
13'th point:
east: True
north: False
west: True
14'th point:
east: True
north: False
west: True
15'th point was out of bounds
16'th point:
east: True
north: False
west: False
17'th point was out of bounds
18'th point:
east: False
north: True
west: False
19'th point:
east: False
north: True
west: False
20'th point was out of bounds
21'th point was out of bounds
22'th point:
east: True
north: False
west: False
23'th point:
east: True
north: False
west: True
24'th point was out of bounds
25'th point was out of bounds
26'th point:
east: False
north: True
west: True
27'th point:
east: False
north: True
west: True
28'th point:
east: True
north: False
west: True
29'th point was out of bounds
30'th point:
east: False
north: False
west: True
31'th point:
east: False
north: False
west: True
32'th point:
east: True
north: False
west: True
33'th point was out of bounds
34'th point:
east: False
north: True
west: False
35'th point:
east: False
north: True
west: False
36'th point:
east: False
north: True
west: False
37'th point:
east: False
north: True
west: False
38'th point:
east: True
north: True
west: True
39'th point:
east: True
north: True
west: True
40'th point:
east: True
north: False
west: True
41'th point:
east: True
north: False
west: True
42'th point:
east: False
north: False
west: True
43'th point was out of bounds
44'th point:
east: True
north: False
west: False
45'th point:
east: True
north: False
west: False
46'th point:
east: True
north: True
west: True
47'th point:
east: False
north: False
west: True
48'th point:
east: False
north: False
west: True
49'th point:
east: True
north: True
west: True
50'th point was out of bounds
51'th point:
east: True
north: False
west: False
52'th point was out of bounds
53'th point was out of bounds
54'th point was out of bounds
55'th point:
east: False
north: True
west: False
56'th point:
east: True
north: True
west: True
57'th point:
east: True
north: True
west: False
58'th point:
east: True
north: True
west: True
59'th point:
east: True
north: True
west: True
60'th point:
east: True
north: False
west: True
61'th point:
east: True
north: False
west: False
62'th point was out of bounds
63'th point was out of bounds
64'th point was out of bounds
65'th point:
east: True
north: False
west: True
66'th point was out of bounds
67'th point:
east: True
north: True
west: True
68'th point was out of bounds
69'th point was out of bounds
70'th point:
east: True
north: False
west: False
71'th point was out of bounds
72'th point was out of bounds
73'th point:
east: False
north: True
west: True
74'th point was out of bounds
75'th point:
east: True
north: True
west: True
76'th point was out of bounds
77'th point was out of bounds
78'th point:
east: True
north: False
west: False
79'th point:
east: True
north: False
west: True
80'th point:
east: True
north: False
west: True
81'th point:
east: True
north: False
west: True
82'th point was out of bounds
83'th point:
east: False
north: False
west: True
84'th point was out of bounds
85'th point:
east: True
north: False
west: True
86'th point:
east: False
north: False
west: True
87'th point:
east: True
north: False
west: True
88'th point:
east: False
north: True
west: False
89'th point:
east: False
north: True
west: False
90'th point:
east: False
north: True
west: False
91'th point:
east: True
north: True
west: True
92'th point:
east: True
north: False
west: True
93'th point:
east: True
north: False
west: True
94'th point was out of bounds
95'th point was out of bounds
96'th point was out of bounds
97'th point:
east: True
north: False
west: True
98'th point:
east: True
north: True
west: True
99'th point:
east: True
north: False
west: True
100'th point:
east: False
north: True
west: False
101'th point:
east: False
north: True
west: False
102'th point was out of bounds
103'th point:
east: False
north: False
west: True
104'th point:
east: True
north: False
west: True
105'th point was out of bounds
106'th point was out of bounds
107'th point:
east: True
north: True
west: True
108'th point:
east: False
north: True
west: False
109'th point:
east: True
north: False
west: True
110'th point was out of bounds
111'th point:
east: False
north: False
west: True
112'th point:
east: True
north: True
west: False
113'th point was out of bounds
114'th point:
east: True
north: False
west: True
115'th point was out of bounds
116'th point:
east: True
north: False
west: True
117'th point was out of bounds
118'th point was out of bounds
119'th point:
east: True
north: False
west: True
120'th point:
east: True
north: False
west: False
121'th point was out of bounds
122'th point was out of bounds
123'th point was out of bounds
124'th point:
east: True
north: False
west: True
125'th point:
east: True
north: False
west: True
126'th point was out of bounds
127'th point was out of bounds
128'th point:
east: False
north: False
west: True
129'th point:
east: False
north: False
west: True
130'th point:
east: True
north: False
west: True
131'th point:
east: False
north: False
west: True
132'th point:
east: False
north: True
west: False
133'th point:
east: False
north: True
west: False
134'th point:
east: False
north: True
west: False
135'th point:
east: False
north: True
west: False
136'th point:
east: False
north: True
west: False
137'th point:
east: False
north: True
west: False
138'th point was out of bounds
139'th point:
east: False
north: True
west: False

/var/folders/y4/0rshr7xn6wg1prq0wx_jcmzw0000gn/T/ipykernel_36197/3818094810.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  coord = coord[1][0].split(",")